pvpLocation: world -94 91 32 -90 0

rankingHolograms:
  totalKills: world -147.5 7.5 -318
  bestKS: world -142.5 7.5 -318

safeZone:
  ==: fr.olympa.api.region.shapes.ExpandedCuboid
  world: "world"
  xMin: -220
  zMin: -340
  xMax: -75
  zMax: -220

killbox:
  ==: fr.olympa.api.region.shapes.Cuboid
  world: "world"
  xMin: 0
  yMin: 0
  zMin: 0
  xMax: 1
  yMax: 1
  zMax: 1